2020-06-22 19:06:41,244 ERROR: Exception on /edit_profile [POST]             [in /home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py: 1892]
Traceback (most recent call last):
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/cat/Dev/microblog/app/routes.py", line 88, in edit_profile
    db.session.commit()
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 995, in _emit_update_statements
    statement, multiparams
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('susan', 'I like cats', 2)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-07-04 16:37:50,225 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 16:38:17,255 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 16:38:43,852 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 16:38:58,124 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 16:42:25,383 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 17:57:38,040 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 17:58:53,800 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 18:00:33,544 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 18:00:57,178 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 18:01:03,887 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 19:13:23,638 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 19:13:41,169 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 19:26:04,470 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 19:26:10,570 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 19:26:48,772 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
2020-07-04 19:26:59,485 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:52]
