2020-07-09 20:45:18,678 ERROR: Exception on / [GET] [in /home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/cat/Dev/microblog/app/main/routes.py", line 48, in index
    prev_url=prev_url)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/cat/Dev/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/cat/Dev/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 26, in block "body"
    {% block scripts %}
  File "/home/cat/Dev/microblog/app/templates/base.html", line 136, in block "scripts"
    $.ajax('{{ url_for('main.notifications') }}?since=' + since).done(
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.notifications'. Did you mean 'main.unfollow' instead?
2020-07-09 20:46:05,769 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-09 20:46:35,921 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 17:47:14,768 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 17:48:16,858 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 17:51:32,899 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 17:54:35,693 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 17:55:22,848 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 17:55:38,662 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 17:55:56,395 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 17:56:45,222 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 18:00:31,835 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 18:02:46,130 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 18:04:37,494 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 18:04:50,053 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 18:04:59,405 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:77]
2020-07-11 18:23:26,743 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:81]
2020-07-11 18:24:39,879 ERROR: Exception on /user/susan [GET] [in /home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/cat/Dev/microblog/app/main/routes.py", line 79, in user
    next_url=next_url, prev_url=prev_url, form=form)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/cat/Dev/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/cat/Dev/microblog/app/templates/user.html", line 69, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2020-07-11 18:26:23,404 INFO: Microblog startup [in /home/cat/Dev/microblog/app/__init__.py:81]
